version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: deuro_monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-securepassword}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  monitoring:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database Configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: deuro_monitoring
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD:-securepassword}
      DB_SSL: false
      
      # Blockchain Configuration  
      RPC_URL: ${RPC_URL}
      DEPLOYMENT_BLOCK: ${DEPLOYMENT_BLOCK}
      BLOCKCHAIN_ID: ${BLOCKCHAIN_ID:-1}
      
      # Monitoring Configuration
      MONITORING_INTERVAL: ${MONITORING_INTERVAL:-300000}
      
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data: